name: Something isn’t working
description: Report a bug or a problem you ran into (no technical knowledge required).
title: "Problem: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking a moment to report this.
        You don’t need to be technical. A short description is enough.

  - type: textarea
    id: what-you-wanted
    attributes:
      label: What were you trying to do?
      placeholder: "Example: I tried to reply to an arrived note…"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened instead?
      placeholder: "Example: It showed an error / it didn’t send / it got stuck…"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if you can)
      description: Optional, but helpful. Even rough steps are fine.
      placeholder: |
        1) …
        2) …
        3) …
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Where did it happen?
      options:
        - Not sure
        - Sign in / account
        - Create note
        - Arrival / reply
        - Chain view / trail
        - Profile / settings
        - Reports / delete
        - Localization / language
        - Other
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device (optional)
      description: If you know it, e.g. iPhone 14, Pixel 7, Windows PC.
      placeholder: "Example: iPhone 14"
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser / app mode (optional)
      description: If you know it, e.g. Safari, Chrome, PWA mode.
      placeholder: "Example: Safari (PWA)"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot (optional)
      description: You can paste an image here if it helps. Please avoid personal info.
      placeholder: "Paste or drag an image here (optional)."
    validations:
      required: false

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy check
      options:
        - label: I did not include private note content, emails, or personal info.
          required: true
