name: Thoughts or feedback
description: Share a small piece of feedback. Feelings and first impressions are welcome.
title: "Feedback: "
labels:
  - feedback
body:
  - type: markdown
    attributes:
      value: |
        Thank you for leaving a note here.
        This can be short. One sentence is enough.

  - type: textarea
    id: feeling
    attributes:
      label: What did Driftya feel like?
      placeholder: "Example: Calm, confusing, comforting, too empty, too fast…"
    validations:
      required: true

  - type: textarea
    id: moment
    attributes:
      label: What moment caused that feeling? (optional)
      placeholder: "Example: When I hit the text limit / when a note arrived / when it timed out…"
    validations:
      required: false

  - type: textarea
    id: wish
    attributes:
      label: If you could change one thing (optional)
      placeholder: "Example: I wish the limit was clearer / I wish it was slower / I wish I could…"
    validations:
      required: false

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy check
      options:
        - label: I did not include private note content, emails, or personal info.
          required: true
